# Generated by Django 2.0.2 on 2022-07-05 19:55

from django.db import migrations, models
import ejemplos.models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to=ejemplos.models.custom_upload_to)),
                ('product_state', models.CharField(blank=True, default='No', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
    ]
