# Generated by Django 2.0.2 on 2022-07-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=240, null=True, upload_to=''),
        ),
    ]
