# Generated by Django 2.0.2 on 2022-07-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0003_auto_20220705_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
