# Generated by Django 2.0.2 on 2023-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0006_category_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_last_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
